server:
  servlet:
    context-path: /api
  port:

spring:
  application:
    name: identity-service
  config:
    import: optional:configtree:/run/secrets/
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    password: ${db_password}
    username:
    url:

  kafka:
    bootstrap-servers:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone:

kafka:
  producer:
    customer-user:
      topic: main-customer-user

    representative-user:
      topic: main-representative-user

  consumer:
    representative:
      main-groupId: main-representative-group
      main-topic: main-representative
      dlq-topic: dlq-representative

jwt:
  secret: ${jwt_secret}
  token-expiration: